ARG VAQ_IMAGE=ghcr.io/xschahl/vaquila:v0.1.0-beta.1
FROM ${VAQ_IMAGE}

LABEL org.opencontainers.image.title="vAquila Runtime Wrapper"
LABEL org.opencontainers.image.description="Wrapper image that pins a vAquila runtime image from GHCR"
